# Generated by Django 4.1.1 on 2022-09-21 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 15, 29, 15, 491551, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
